kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rolebinding.name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: Group
    name: system:serviceaccounts:{{ .Release.Namespace }} # All svc accounts of ingress-basic namespaces
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.roleBinding.roleRefName }} # A references to the role above
  apiGroup: rbac.authorization.k8s.io