{{- if .Values.circuit.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.circuit.name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.circuit.serviceName }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutiveErrors: {{ .Values.circuit.consecutiveErrors }}
      interval: {{ .Values.circuit.interval }}
      baseEjectionTime: {{ .Values.circuit.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.circuit.maxEjectionPercent }}
{{- end }}