{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "virtualservice.name" . }}-beta
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.candidatevirtualservice.hosts }}
  http:
{{ toYaml .Values.vsroutes | indent 4 }}
{{- end }}
